### ISSUE TITLE
More information needed on the Readme

### ISSUE THREAD

**Issue by rozzilla** [BrainStormDevel/perseo#1]
Hello! :)
Your project seems interesting to me, but I think that there are not enough instructions on the Readme.
It'd be more useful to clearly understand how to install it, how it works and what are the main features.
Have a nice day! :+1:

**Comment by BrainStormDevel** [comment]
Hi, thanks for your interest.
To install the cms is really simple. Just git clone or download the project, rename the htaccess files and use composer to install dependencies. After that, go to http://yourhost/install and you can see the Wizard help you to configure the basic feature.

**Comment by BrainStormDevel** [comment]
After the configuration, you can write your own test module in the modules folder. In the next commit, I will add some test modules to show how simple and powerful is this project.

**Comment by BrainStormDevel** [comment]
Readme updated.

**Comment by rozzilla** [comment]
That's great! I'll close this issue :+1:
