### ISSUE TITLE
Can't create new module

### ISSUE THREAD

**Issue by vrobbi** [BrainStormDevel/perseo#21]
Installation create new tables, but they are empty. 
Then I tried to create new module following what the poor doc says, but i got the error not found

**Comment by BrainStormDevel** [comment]
Hello.
Those tables are empty because it's not used for now.
For the error not found, you must use the prefix /it/ or /en/ on your route because Locale middleware is enabled by default. You can disable it in the wizard or set the "locale" variable in the settings.php to false to disable it.
