### ISSUE TITLE
Indentazione dei file sorgente

### ISSUE THREAD

**Issue by francescobianco** [BrainStormDevel/perseo#3]
Ciao, noto che tutti i file sorgente php si leggono male l'indentazione non viene rispettata,
ti consiglio di inserire nel progetto questo importantissimo tool

https://styleci.io/

credimi di da un sacco di vantaggi

per esempio guarda la riga 10 in questa screenshoot
![Screenshot 2019-04-02 at 02 19 50](https://user-images.githubusercontent.com/472171/55367551-f1aadd80-54ed-11e9-9feb-99881e8155c2.png)

Ciao

**Comment by BrainStormDevel** [comment]
Ottimo, grazie del consiglio. A breve aggiornerò tutto il CMS visto che ho fatto importanti upgrade (sono passato a Slim framework per via di PSR-7).

**Comment by BrainStormDevel** [comment]
Codice ri-formattato secondo standard PSR-2.

**Comment by francescobianco** [comment]
@BrainStormDevel controlla bene i TAB e gli SPAZI nei vari file, ti consiglio StyleCI che ti crea delle pull request correttive che fixano i tuoi file... leggi qui come installarlo

https://styleci.readme.io/docs/getting-started

in questo file vedi ancora come i tab e gli spazi sono tutti scomposti non seguono nessuna line verticale di indentazione....

![Screenshot 2019-05-08 at 11 54 19](https://user-images.githubusercontent.com/472171/57366855-231b6680-7188-11e9-8bea-c7c9d8804a70.png)
