### ISSUE TITLE
StyleCI e Trevis CI

### ISSUE THREAD

**Issue by francescobianco** [BrainStormDevel/perseo#5]
Consiglio l'utilizzo di TravisCI e StyleCI approfondimenti in questo ticket 
https://github.com/BrainStormDevel/perseo/issues/3

**Comment by BrainStormDevel** [comment]
Verifico, per il resto hai avuto modo di provare la nuova struttura? In questi giorni farò ulteriori modifiche ottimizzando la classe Login e Sanitize.

**Comment by BrainStormDevel** [comment]
Implementato proprio ora.

**Comment by francescobianco** [comment]
Non vedo nessun link nel readme e neanche il file .styleci.yml

**Comment by BrainStormDevel** [comment]
Ho collegato il repo al servizio styleci.io e ho creato un commit ripulito da loro.
